name: Build and Release Executable with Auto-Increment Tag

on:
  push:
    branches:
      - main

jobs:
  prepare-tag:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.new_tag.outputs.tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --local user.email "dmitri.ollari@protonmail.com"
          git config --local user.name "kanopo"

      - name: Fetch Tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Determine New Tag
        id: new_tag
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Latest tag: $latest_tag"
          new_tag="${latest_tag%.*}.$((${latest_tag##*.}+1))"
          echo "New tag: $new_tag"
          echo "::set-output name=tag::$new_tag"

      - name: Create and Push New Tag
        run: |
          new_tag=${{ steps.new_tag.outputs.tag }}
          git tag $new_tag
          git push https://${{ secrets.MY_PAT }}@github.com/kanopo/image-escavator.git $new_tag

  build-windows:
    needs: prepare-tag
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build Executable
        run: pyinstaller --onefile main.py

      - name: Upload Executable to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: image-escavator-windows
          path: dist/*.exe

  build-linux:
    needs: prepare-tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build Executable
        run: pyinstaller --onefile main.py

      - name: Upload Executable to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: image-escavator-linux
          path: dist/main

  build-macos:
    needs: prepare-tag
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build Executable
        run: pyinstaller --onefile main.py

      - name: Upload Executable to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: image-escavator-macos
          path: dist/main

  release:
    needs: [build-windows, build-linux, build-macos]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download Windows Artifact
        uses: actions/download-artifact@v2
        with:
          name: image-escavator-windows
          path: artifacts/windows

      - name: Download Linux Artifact
        uses: actions/download-artifact@v2
        with:
          name: image-escavator-linux
          path: artifacts/linux

      - name: Download macOS Artifact
        uses: actions/download-artifact@v2
        with:
          name: image-escavator-macos
          path: artifacts/macos

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: "Description of the release"

      - name: Upload Windows Executable
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/windows/image-escavator-windows.exe
          asset_name: image-escavator-windows.exe
          asset_content_type: application/octet-stream

      - name: Upload Linux Executable
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/linux/main
          asset_name: image-escavator-linux
          asset_content_type: application/octet-stream

      - name: Upload macOS Executable
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/macos/main
          asset_name: image-escavator-macos
          asset_content_type: application/octet-stream
